create table if not exists clients (

    id bigint generated by default as identity,
    name varchar(255) not null,
    age integer check (age>=18),
    phone_number varchar(255) not null,
    email varchar(255),
    primary key (id)
    );

create table if not exists cars (

    id bigint generated by default as identity,
    brand varchar(255) not null,
    model varchar(255) not null,
    colour varchar(255) not null,
    year integer not null,
    number varchar(255) not null,
    owner_id bigint,
    primary key (id)
    );

create table if not exists spot_parking (

    id bigint generated by default as identity,
    floor integer not null,
    spot_number integer not null check (spot_number<=10),
    price_id bigint,
    client_id bigint,
    is_busy boolean,
    primary key (id)
    );

create table if not exists price (

    id bigint generated by default as identity,
    floor integer not null,
    price integer not null,
    primary key (id)
    );

create table if not exists reserve (

    reserve_id bigint generated by default as identity,
    client_id bigint,
    spot_id bigint not null,
    start_reserve timestamp(6),
    end_reserve timestamp(6),
    is_active boolean,
    primary key (reserve_id)
    );

alter table if exists cars
       add constraint fk_car_owner
       foreign key (owner_id)
       references clients(id);

alter table if exists reserve
       add constraint fk_client_reserve
       foreign key (client_id)
       references clients(id);

alter table if exists reserve
       add constraint fk_spot_reserve
       foreign key (spot_id)
       references spot_parking(id);

alter table if exists spot_parking
       add constraint fk_spot_client
       foreign key (client_id)
       references clients(id);

alter table if exists spot_parking
       add constraint fk_spot_price
       foreign key (price_id)
       references price(id);

create index IF NOT EXISTS IDX_cars_owner ON cars(owner_id);
create index IF NOT EXISTS IDX_spot_client ON spot_parking(client_id);
create index IF NOT EXISTS IDX_spot_price ON spot_parking(price_id);
create index IF NOT EXISTS IDX_reserve_client ON reserve(client_id);
create index IF NOT EXISTS IDX_reserve_spot ON reserve(spot_id);